### ISSUE TITLE
Should we differentiate between Image features and Vector features?

### ISSUE THREAD

**Issue by patricksnape** [menpo/menpo#621]
**Image feature**: Yields a multi-channel image. That is, the return vector can be reshaped into an image shape (rectangular) that can be viewed as an image. This image may have multiple channels. Therefore, it is possible to compute a spatial gradient on the result of the feature function.

**Vector feature**: Yields a vector. This vector cannot be easily (or at all) viewed as an image. Taking spatial gradients is impossible. However, this feature may be very discriminative and compact.

At the moment, we have no clear distinction between features that yield a multi-channel image and features that yield a vector. This is particularly important for MenpoFit, where some methods, such as AAMs, require Image features.

Should we differentiate more explicitly between these methods? Features such as HOG are confusing at the moment, in my opinion, as some settings generate images, where as others generate vectors.

**Comment by nontas** [comment]
I believe that this highlights the necessity of having a dummy `Vector` class, as discussed in https://github.com/menpo/menpo/issues/626. Then all feature functions, depending on the options, can either return a (landmarked) `Image` or a `Vector` instance. 

However, I do not believe that we need to have a clear separation between `Image` and `Vector` features  in terms of Python packages, since some features belong to both categories depending on the options (e.g. LBP, HOG).

**Comment by patricksnape** [comment]
As mentioned in the PCA discussion, I don't want any sort of `Vector` class returned!

**Comment by patricksnape** [comment]
HOG etc have been removed so I think this discussion can be reopened if it becomes an issue in the future
