### ISSUE TITLE
Rotating images is backwards

### ISSUE THREAD

**Issue by patricksnape** [menpo/menpo#627]
```
%matplotlib inline

import numpy as np
import menpo.io as mio
from menpo.image import Image
from menpo.transform import rotate_ccw_about_centre

image = mio.import_builtin_asset.takeo_ppm()

t = rotate_ccw_about_centre(image, 45)
image.warp_to_shape(image.shape, t).view_widget()
```

Takeo gets rotated 45 degress **clockwise** - **INCORRECT**!

```
%matplotlib inline

import numpy as np
import menpo.io as mio
from menpo.image import Image
from menpo.transform import rotate_ccw_about_centre

image = mio.import_builtin_asset.takeo_ppm()
bounds = bounding_box((0, 0), image.shape)

t = rotate_ccw_about_centre(bounds, 45)
t.apply(bounds).view_widget()
```

Bounding box of the Takeo image gets rotated 45 degress **counter-clockwise** - **CORRECT**!

**Comment by patricksnape** [comment]
@jabooth Can you confirm I am correct here?

**Comment by nontas** [comment]
Actually there is no mistake here @patricksnape . The `warp_to_shape()` method expects a `Transform` from the rotated space to the image space. As the documentation says:
```
transform : :map:`Transform`
    Transform **from the template_shape space back to this image**.
    Defines, for each index on template_shape, which pixel location
    should be sampled from on this image.
```

This means that in the above Takeo example, you need to do:
```
image.warp_to_shape(image.shape, t.pseudoinverse()).view_widget()
```
and you'll get the correct result. Note that the same is done within the `rotate_ccw_about_centre()` method of the `Image` class, that's why it is working as expected, i.e. counter-clockwise rotation.

**Comment by patricksnape** [comment]
Welp, you are totally right. Now I feel a fool! Closing on embarrassment...
