### ISSUE TITLE
Some image properties missing the @property decorator

### ISSUE THREAD

**Issue by timmmer** [menpo/menpo#662]
In menpo/image/base.py, in the definition of the class Image, some of the class properties (starting with diagonal()  and centre() ) are not preceded by @property .

This breaks at least one of the IPython notebooks:
in notebooks/Images/basics the input:
    print('The centre of Takeo is {}'.format(take.centre))
does not output the desired result.

**Comment by patricksnape** [comment]
Ah! I think this is actually a bug in the notebooks! Note how it says ``The centre of Takeo is <bound method Image.centre of <menpo.image.base.Image object at 0x1061c9e10>>`` as you mentioned (since it's actually a method). 

In Menpo, we tried to be consistent with anything that is computed is a method (and anything that is just property access is a property). This is designed to ensure that Menpo users know that when they need to call a method they should probably cache the value (since methods always compute things rather than just returning values without cost). Since `diagonal` and `centre` compute values, they are methods!

Thanks for pointing out the notebooks errors though! Let me know if you think this is a sensible design as well since it's always good to have people weigh in.

**Comment by timmmer** [comment]
> Thanks for pointing out the notebooks errors though! Let me know if you think this is a sensible design as well since it's always good to have people weigh in.
> 

You’re welcome.

I see, so a property is like a get function. Thanks for the explanation.

Best,
Tim

Tim K. Marks, Ph.D.
Principal Member Research Staff
Mitsubishi Electric Research Labs (MERL)
Cambridge, MA

**Comment by patricksnape** [comment]
Yes at least that was how we decided to treat properties (like getters in other languages). I'm going to close this if that is alright. If you find any inconsistencies like properties that should be methods please do let us know!
