### ISSUE TITLE
menpo 0.7 not available

### ISSUE THREAD

**Issue by Halo-5** [menpo/menpo#686]
The change log cites version 0.7 as available

`http://menpo.readthedocs.io/en/latest/userguide/changelog.html`

but `conda update menpo` shows the most recent as 0.62 and this is also the latest release listed on the home page.

**Comment by patricksnape** [comment]
Yes that was an oversight - the date was automatically generated by the changelog generator. We stalled the 0.7.0 release as I am away at the moment - at the moment there is no firm date on the 0.7.0 release primarily due to testing being required for menpofit at the moment. I have removed the date from the changelog.

0.6.2 is indeed the latest supported released version.

**Comment by jabooth** [comment]
A checklist for the menpo 0.7.0 can be found here: #693

**Comment by jabooth** [comment]
@Halo-5 Menpo 0.7 is now released. We'll be updating the website soon, and menpo3d is lagging behind a little, but you can get the rest of the projects now from conda.
