### ISSUE TITLE
Support for matplotlib 2

### ISSUE THREAD

**Issue by 183amir** [menpo/menpo#781]
Hi,

I am trying to use menpo in an environment with matplotlib 2 but the tests fail with matplotlib 2.
```
======================================================================
FAIL: menpo.image.test.rasterize_test.test_rasterize_matplotlib_basic_line
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/bob/bob.conda/conda-env/menpo_1486546584119/_t_env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builds/bob/bob.conda/conda-env/menpo_1486546584119/_t_env/lib/python2.7/site-packages/menpo/image/test/rasterize_test.py", line 44, in test_rasterize_matplotlib_basic_line
    assert_allclose(new_im.pixels[2, 5:8, 5], [255, 255, 255])
  File "/builds/bob/bob.conda/conda-env/menpo_1486546584119/_t_env/lib/python2.7/site-packages/numpy/testing/utils.py", line 1392, in assert_allclose
    verbose=verbose, header=header)
  File "/builds/bob/bob.conda/conda-env/menpo_1486546584119/_t_env/lib/python2.7/site-packages/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array([223, 223,   0], dtype=uint8)
 y: array([255, 255, 255])
```
I know that matplotlib 2 is not supported but is there any plan to add support for that?

ping @anjos

**Comment by jabooth** [comment]
Hey @183amir!

Is the only test failure case or are there others?

We largely only rely on matplotlib for visulalization not computation, so you should be able to use menpo just perhaps with some rough edges around visualization/widgets.

In general we definitely want to support the latest matplotlib release, so we are totally open to any PR which moves to support matplotlib 2.0. I'll be honest, I haven't looked into it so I'm not sure how much effort it will be to bump the dep..glancing at the changelog it seems to be more that defaults for the styles have changed rather than the API been totally torn up and replaced? If so it could be fairly straightforward...

**Comment by 183amir** [comment]
Only this one fails. And yes, matplotlib 2 is mostly default style changes rather than API.

**Comment by jabooth** [comment]
@183amir interesting, all tests pass with matplotlib 2 for Py 2.7/3.4/3.5 on Linux:
https://travis-ci.org/menpo/menpo/builds/199559397

What platform were you seeing the failure on? Build 379 on our macOS/Win CI box will be the test run for those platforms, should be done in ~20mins:
https://jenkins.menpo.org/job/menpo-pr/

**Comment by 183amir** [comment]
Maybe it's fixed in master? my merge request is here: https://gitlab.idiap.ch/bob/bob.conda/merge_requests/13 we are packaging menpo in our channel. The log is here: https://gitlab.idiap.ch/bob/bob.conda/builds/44282

**Comment by 183amir** [comment]
@jabooth the failing tests are skipped in travis-ci:
```
menpo.image.test.rasterize_test.test_rasterize_matplotlib_basic ... SKIP: Skipping due to lack of DISPLAY on Travis

menpo.image.test.rasterize_test.test_rasterize_matplotlib_basic_line ... SKIP: Skipping due to lack of DISPLAY on Travis

menpo.image.test.rasterize_test.test_rasterize_pillow_basic ... SKIP: Skipping due to lack of DISPLAY on Travis

menpo.image.test.rasterize_test.test_rasterize_pillow_basic_line ... SKIP: Skipping due to lack of DISPLAY on Travis
```

**Comment by jabooth** [comment]
Ah yes, very true. In general we've had issues with unit tests on visualisation stuff been finicky (especially across platforms) so will just need to look here if this is really a breaking change or just a slight difference in pixel output.

I wasn't aware of Bob before, nice work!

Btw, there's a reasonable diff between master `v0.7.7` due to the landmarks change we just landed:
https://github.com/menpo/menpo/compare/v0.7.7...master

You might find the landmarks change impacts you slightly once menpo `v0.8.x` comes out. I was going to take a look for myself to see if I could offer some pointers but couldn't see the code for the module which I assume is here? https://gitlab.idiap.ch/bob/bob.ip.facelandmarks

**Comment by 183amir** [comment]
Yes it is there. Sorry there was a problem with its visibility: https://gitlab.idiap.ch/bob/bob.ip.facelandmarks please try again.

**Comment by patricksnape** [comment]
Unfortunately we can't upgrade until we manage to get Mayavi to work with QT 5 (which Matplotlib 2.0 on conda now requires)

**Comment by 183amir** [comment]
Sorry @patricksnape but I don't see menpo (this repo) depending on Mayavi? Does it? I am not talking about upgrading your channel/stack to matplotlib 2. I am talking about supporting matplotlib 2 in this package (menpo). We already package menpo and some few other menpo related packages in our own channel.

**Comment by patricksnape** [comment]
menpo3d relies on mayavi and having matplotib 2.0 would prevent us from installing menpo3d in the same environment. Having said that, I'm not averse to seeing if we can make sure the code works with both matplotlib 1.x and 2.x

**Comment by patricksnape** [comment]
This has been merged as Mayavi now works on conda-forge
